[project]
name = "devcontainer-images"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=3.8.0",
]

[tool.uv]
dev-dependencies = [
    "invoke>=2.2.0",
    "ruff>=0.6.7",
]
